language: r
cache: packages
warnings_are_errors: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
env:
  global:
  - CXX=g++-8
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
  - MAKEFLAGS="-j 2"
before_install:
- mkdir -p ~/.R
- echo "CXX = $CXX" > ~/.R/Makevars
- echo "CXX14 = $CXX" >> ~/.R/Makevars
- echo "CXX14FLAGS = $(R CMD config CXXFLAGS) -fPIC" >> ~/.R/Makevars
matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov(type = "all")'
  - r: oldrel
branches:
  except:
  - "/^v?\\d+\\.\\d+/"
notifications:
  email: false
  slack:
    secure: SxF5Q6dHORBkbUOmLsSe++S/GwnJ3pz70usQch/L1rBG8qWwVBkeTJkRhv0JPMToDHW8SVxpi1CiGJRh/m2vm1B7v/oppATcdck9TUxcYcSAua6KjdMDgEaZQvco1YKbooRPVtJIp1kqC5PUkf+Z8GfkTa64by+uYfx6UHqeVGRaQHkvV1hdllVogoA1g1CpCwgaOilG3Doc2Pq+ZgYLIjYEZCuecyT53u2Rrlajc3GPcAmrS1bCGkdO4NIkSW7fRmv9rkXxaHPtzkTldcJpMTvC8sOQdmWIN97WW+ogKplRih7Sa+PWhUvKGXS5yloZD6h2a8Y44PRTN+dstmt926xtPJbJ7WC7ZvaUKpsltU+Y/VkPLpqsdDKFMsXs2z+20uDBPpaDIx+L7wMHmQi37Ip7DHuR/mCpSOt14SgLe38fNN6hoT6Dr3Csr8CGce6AJcvdAG7p8EhNc65NUxJeRC9UbWgdgIcEOp+8LAud7TSXd0Znu5fiBf0FqMiY/iC6fCEc+p8VnmtFJEr5lGZzM/x2WU35PQScBfPwMzJ7Fkj3VwXewNsKY3k/t27kxKWLA92udALL6uNjlUwjzlLZyBBV9SHOu030u/FCpNb20UAJlxuVtEsBYx2UT/Jk4P9zO4nPoj+eq8xwNzT2Icz4JbpL24KEinb5JeETw8v//Gc=
